/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsa;

import javax.swing.JFrame;

/**
 *
 * @author kasidet
 */
public class ChooseCustomer extends javax.swing.JFrame {

    /**
     * Creates new form ChooseCustomerPanel
     */
    private int checking;
    
    public ChooseCustomer() {
        initComponents();
    }

    public ChooseCustomer(int checking) {
        initComponents();
        this.checking = checking;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        AddnewPanel1 = new javax.swing.JPanel();
        AddnewLabel1 = new javax.swing.JLabel();
        AddnewPanel = new javax.swing.JPanel();
        AddnewLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        AddnewPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        AddnewPanel1.setOpaque(false);

        AddnewLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        AddnewLabel1.setForeground(new java.awt.Color(204, 255, 0));
        AddnewLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/customer.png"))); // NOI18N
        AddnewLabel1.setText("Exist customer");
        AddnewLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AddnewLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddnewLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddnewLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddnewLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddnewPanel1Layout = new javax.swing.GroupLayout(AddnewPanel1);
        AddnewPanel1.setLayout(AddnewPanel1Layout);
        AddnewPanel1Layout.setHorizontalGroup(
            AddnewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddnewLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddnewPanel1Layout.setVerticalGroup(
            AddnewPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddnewLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AddnewPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        AddnewPanel.setOpaque(false);

        AddnewLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 48)); // NOI18N
        AddnewLabel.setForeground(new java.awt.Color(0, 255, 0));
        AddnewLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/customer.png"))); // NOI18N
        AddnewLabel.setText("Add new customer");
        AddnewLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        AddnewLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddnewLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddnewLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddnewLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout AddnewPanelLayout = new javax.swing.GroupLayout(AddnewPanel);
        AddnewPanel.setLayout(AddnewPanelLayout);
        AddnewPanelLayout.setHorizontalGroup(
            AddnewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddnewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );
        AddnewPanelLayout.setVerticalGroup(
            AddnewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AddnewLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddnewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(AddnewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AddnewPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddnewPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddnewLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddnewLabelMouseClicked
        AddnewCustomer addnewCustomer = new AddnewCustomer();
        addnewCustomer.show();
        addnewCustomer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AddnewLabelMouseClicked

    private void AddnewLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddnewLabel1MouseClicked
        ExistCustomer existcustomer = new ExistCustomer(checking);
        existcustomer.show();
        existcustomer.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_AddnewLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddnewLabel;
    private javax.swing.JLabel AddnewLabel1;
    private javax.swing.JPanel AddnewPanel;
    private javax.swing.JPanel AddnewPanel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
