/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsa;

import method.ReadAccess;
import javax.swing.JOptionPane;

/**
 *
 * @author kasidet
 */
public class ExistCustomer extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    private boolean isSaving;
    private String phonenm;
    private int checking;

    public ExistCustomer() {
        initComponents();
        isSaving = false;
    }

    public ExistCustomer(int checking) {
        initComponents();
        this.checking = checking;
        isSaving = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TFPhone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ConfirmLabel = new javax.swing.JLabel();
        SaveLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Equipment rental store");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/real-estate.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/phone-call.png"))); // NOI18N

        TFPhone.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone");

        ConfirmLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ConfirmLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfirmLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/verified.png"))); // NOI18N
        ConfirmLabel.setText("Confirm");
        ConfirmLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConfirmLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ConfirmLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmLabelMouseClicked(evt);
            }
        });

        SaveLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        SaveLabel.setForeground(new java.awt.Color(255, 255, 255));
        SaveLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SaveLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/diskette.png"))); // NOI18N
        SaveLabel.setText("Save data");
        SaveLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(TFPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(SaveLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ConfirmLabel)
                .addGap(17, 17, 17))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TFPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConfirmLabel)
                    .addComponent(SaveLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmLabelMouseClicked
        if (isSaving) {
            if (!phonenm.isEmpty()) {
                String[] customer = new ReadAccess().retrieveCustomerID(phonenm);
                if (customer == null) {
                    JOptionPane.showMessageDialog(this, "Phone number is not register!", "Equipment rental store", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                String fn = customer[1];
                String ln = customer[2];
                String address = customer[3];
                String email = customer[4];
                int confirm = JOptionPane.showConfirmDialog(this, "Data customer\nFirst name: " + fn + "\nLast name: " + ln + "\nAddress: " + address + "\nEmail: " + email + "\nPhone number: " + phonenm, "Equipment rental store", JOptionPane.YES_NO_OPTION);
                if (checking == 1) {
                    JOptionPane.showMessageDialog(this, "Data customer\nFirst name: " + fn + "\nLast name: " + ln + "\nAddress: " + address + "\nEmail: " + email + "\nPhone number: " + phonenm, "Equipment rental store", JOptionPane.INFORMATION_MESSAGE);
                } else if (checking == 2) {
                    int customerId = Integer.parseInt(customer[0]);
                    Boolean checkrent = new ReadAccess().retrieveRentItem(customerId);
                    if (checkrent == true) {
                        new ReturnItem(customerId, fn, ln, address, email, phonenm).setVisible(true);
                        this.dispose();
                    } else {
                        this.dispose();
                    }

                } else {
                    if (confirm == JOptionPane.YES_OPTION) {
                        int customerId = Integer.parseInt(customer[0]);
                        new Invoice(customerId, fn, ln, address, email, phonenm).setVisible(true);
                        this.dispose();
                    }
                }

            } else {
                JOptionPane.showMessageDialog(this, "Somefield is empty", "Equipment rental store", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please save data first!", "Equipment rental store", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmLabelMouseClicked

    private void SaveLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveLabelMouseClicked
        phonenm = TFPhone.getText();
        if (SaveLabel.getText().equalsIgnoreCase("Save Data")) {
            if (!phonenm.isEmpty()) {
                TFPhone.disable();
                SaveLabel.setText("Change data");
                isSaving = true;
            } else {
                JOptionPane.showMessageDialog(this, "Please fill in all fields", "Equipment rental store", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            SaveLabel.setText("Save Data");
            TFPhone.enable();
            TFPhone.setText("");
            isSaving = false;
        }

    }//GEN-LAST:event_SaveLabelMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmLabel;
    private javax.swing.JLabel SaveLabel;
    private javax.swing.JTextField TFPhone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
