/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsa;

import method.SaveAccess;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.*;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;

/**
 *
 * @author kasidet
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Cart
     */
    private String[][] datatable;
    private int customerid;
    private final JTable cartTable = Main.TableCart;

    public Invoice(int customerid, String fn, String ln, String address, String email, String phone) {
        initComponents();
        this.customerid = customerid;
        TableModel model = cartTable.getModel();
        TableCart.setModel(model);
        datatable = new String[TableCart.getRowCount()][8];
        FirstnameLabel.setText(fn);
        LastNameLabel.setText(ln);
        AddressLabel.setText(address);
        EmailLabel.setText(email);
        PhoneLabel.setText(phone);

        for (int i = 0; i < TableCart.getRowCount(); i++) {
            datatable[i][0] = String.valueOf(TableCart.getValueAt(i, 0));
            datatable[i][1] = String.valueOf(TableCart.getValueAt(i, 1));
            datatable[i][2] = String.valueOf(TableCart.getValueAt(i, 2));
            datatable[i][3] = String.valueOf(TableCart.getValueAt(i, 3));
            datatable[i][4] = String.valueOf(TableCart.getValueAt(i, 4));
            datatable[i][5] = String.valueOf(TableCart.getValueAt(i, 5));
            datatable[i][6] = String.valueOf(TableCart.getValueAt(i, 6));
            datatable[i][7] = String.valueOf(TableCart.getValueAt(i, 7));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ConfirmLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableCart = new javax.swing.JTable();
        FirstnameLabel = new javax.swing.JLabel();
        AddressLabel = new javax.swing.JLabel();
        EmailLabel = new javax.swing.JLabel();
        LastNameLabel = new javax.swing.JLabel();
        PhoneLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI Symbol", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Invoice");

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/real-estate.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/id-card.png"))); // NOI18N
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/location.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/email.png"))); // NOI18N

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/phone-call.png"))); // NOI18N

        ConfirmLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        ConfirmLabel.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ConfirmLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/verified.png"))); // NOI18N
        ConfirmLabel.setText("Confirm");
        ConfirmLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ConfirmLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ConfirmLabel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ConfirmLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfirmLabelMouseClicked(evt);
            }
        });

        TableCart.setBackground(new java.awt.Color(153, 153, 153));
        TableCart.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TableCart.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        TableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "เลขสิ่งของ", "ชนิด", "แบรนด์", "รุ่น", "ค่ายืมรายวัน", "ค่าเช่าเกินกำหนด", "เช่าถึงวันที่", "ราคารวม"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TableCart.setFocusable(false);
        TableCart.setRowHeight(25);
        TableCart.setSelectionBackground(new java.awt.Color(153, 153, 153));
        TableCart.setSelectionForeground(new java.awt.Color(102, 102, 102));
        TableCart.getTableHeader().setReorderingAllowed(false);
        TableCart.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TableCartPropertyChange(evt);
            }
        });
        jScrollPane3.setViewportView(TableCart);

        FirstnameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        FirstnameLabel.setForeground(new java.awt.Color(255, 255, 255));
        FirstnameLabel.setText("-");

        AddressLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        AddressLabel.setForeground(new java.awt.Color(255, 255, 255));
        AddressLabel.setText("-");

        EmailLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        EmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        EmailLabel.setText("-");

        LastNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        LastNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        LastNameLabel.setText("-");

        PhoneLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        PhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        PhoneLabel.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(ConfirmLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FirstnameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(LastNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel1))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(FirstnameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LastNameLabel)
                                .addGap(81, 81, 81)
                                .addComponent(AddressLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(EmailLabel)
                                .addGap(52, 52, 52))
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PhoneLabel)
                                    .addComponent(ConfirmLabel)))))
                    .addComponent(jScrollPane3))
                .addGap(18, 18, 18))
        );

        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfirmLabelMouseClicked
        SimpleDateFormat formater = new SimpleDateFormat("dd/MM/yyyy");
        int confirm = JOptionPane.showConfirmDialog(this, "Confirm order?", "Equipment rental store", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate now = LocalDate.now();
            for (String data[] : datatable) {
                int equipmentId = Integer.parseInt(data[0]);
                LocalDate rentalDate = now;
                double rentalPrice = Double.parseDouble(data[4]);
                double lateFee = Double.parseDouble(data[5]);
                LocalDate returnDate = LocalDate.parse(data[6], formatter);
                double totalprice = Double.parseDouble(data[7]);
                new SaveAccess().Saverentdatarent(equipmentId, customerid, rentalDate, returnDate, rentalPrice, lateFee, totalprice);
                JOptionPane.showMessageDialog(null, "Order success!", "Equipment rental store", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please save data first!", "Equipment rental store", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ConfirmLabelMouseClicked

    private void TableCartPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TableCartPropertyChange
        TableCart.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 14));
        TableCart.getTableHeader().setBackground(new Color(153, 153, 153));
        TableCart.getTableHeader().setOpaque(false);
    }//GEN-LAST:event_TableCartPropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLabel;
    private javax.swing.JLabel ConfirmLabel;
    private javax.swing.JLabel EmailLabel;
    private javax.swing.JLabel FirstnameLabel;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JLabel PhoneLabel;
    public javax.swing.JTable TableCart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
