/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectsa;

import javax.swing.JFrame;

/**
 *
 * @author kasidet
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelMain = new javax.swing.JPanel();
        ListitemPanel = new javax.swing.JPanel();
        ViewItemButton = new javax.swing.JLabel();
        CustomerPanel = new javax.swing.JPanel();
        CustomerButton = new javax.swing.JLabel();
        ReturnPanel = new javax.swing.JPanel();
        ReturnButton = new javax.swing.JLabel();
        RentPanel = new javax.swing.JPanel();
        RentalButton = new javax.swing.JLabel();
        icon = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equipment rental shop");
        setResizable(false);

        jPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMain.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ListitemPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ViewItemButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ViewItemButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/packaging.png"))); // NOI18N
        ViewItemButton.setText("ดูสินค้าทั้งหมด");
        ViewItemButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ViewItemButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ViewItemButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ViewItemButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ViewItemButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ListitemPanelLayout = new javax.swing.GroupLayout(ListitemPanel);
        ListitemPanel.setLayout(ListitemPanelLayout);
        ListitemPanelLayout.setHorizontalGroup(
            ListitemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListitemPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ViewItemButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        ListitemPanelLayout.setVerticalGroup(
            ListitemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListitemPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(ViewItemButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        CustomerPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CustomerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CustomerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/customermain.png"))); // NOI18N
        CustomerButton.setText("ข้อมูลลูกค้า");
        CustomerButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        CustomerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CustomerButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CustomerButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout CustomerPanelLayout = new javax.swing.GroupLayout(CustomerPanel);
        CustomerPanel.setLayout(CustomerPanelLayout);
        CustomerPanelLayout.setHorizontalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(CustomerButton)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        CustomerPanelLayout.setVerticalGroup(
            CustomerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(CustomerButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ReturnPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ReturnButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ReturnButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/return.png"))); // NOI18N
        ReturnButton.setText("คืนสินค้า");
        ReturnButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        ReturnButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ReturnButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ReturnButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ReturnPanelLayout = new javax.swing.GroupLayout(ReturnPanel);
        ReturnPanel.setLayout(ReturnPanelLayout);
        ReturnPanelLayout.setHorizontalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(ReturnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        ReturnPanelLayout.setVerticalGroup(
            ReturnPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ReturnPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ReturnButton)
                .addGap(23, 23, 23))
        );

        RentPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        RentalButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RentalButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/trolley.png"))); // NOI18N
        RentalButton.setText("เช่าสินค้า");
        RentalButton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        RentalButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RentalButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        RentalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RentalButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RentPanelLayout = new javax.swing.GroupLayout(RentPanel);
        RentPanel.setLayout(RentPanelLayout);
        RentPanelLayout.setHorizontalGroup(
            RentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RentalButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RentPanelLayout.setVerticalGroup(
            RentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RentalButton)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout PanelMainLayout = new javax.swing.GroupLayout(PanelMain);
        PanelMain.setLayout(PanelMainLayout);
        PanelMainLayout.setHorizontalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListitemPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelMainLayout.setVerticalGroup(
            PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMainLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ReturnPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ListitemPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CustomerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.add(PanelMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 680, -1));

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/1920x1080-black-solid-color-background.jpg"))); // NOI18N
        icon.setOpaque(true);
        jPanel2.add(icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 700, 260));

        jMenu1.setText("Check data customer");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RentalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentalButtonMouseClicked
        Main main = new Main();
        main.show();
        main.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_RentalButtonMouseClicked

    private void ViewItemButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ViewItemButtonMouseClicked
        Viewitems vi = new Viewitems();
        vi.show();
        vi.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ViewItemButtonMouseClicked

    private void CustomerButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerButtonMouseClicked
        int checking = 1;
        ChooseCustomer cc = new ChooseCustomer(checking);
        cc.show();
        cc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_CustomerButtonMouseClicked

    private void ReturnButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnButtonMouseClicked
        int checking = 2;
        ExistCustomer ec = new ExistCustomer(checking);
        ec.show();
        ec.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_ReturnButtonMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        ViewCustomer vc = new ViewCustomer();
        vc.show();
        vc.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerButton;
    private javax.swing.JPanel CustomerPanel;
    private javax.swing.JPanel ListitemPanel;
    private javax.swing.JPanel PanelMain;
    private javax.swing.JPanel RentPanel;
    private javax.swing.JLabel RentalButton;
    private javax.swing.JLabel ReturnButton;
    private javax.swing.JPanel ReturnPanel;
    private javax.swing.JLabel ViewItemButton;
    private javax.swing.JLabel icon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
