package projectsa;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import method.ReadAccess;
import method.SaveAccess;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author kasidet
 */
public class ReturnItem extends javax.swing.JFrame {

    /**
     * Creates new form ReturnItem
     */
    private int[] selectedRows;
    String selectedRowsString;
    private DefaultTableModel model;
    private int customerid;
    private double totalprice;

    public ReturnItem(int customerid, String fn, String ln, String address, String email, String phonenumber) {
        initComponents();
        this.customerid = customerid;
        totalprice = 0.0;
        model = (DefaultTableModel) RentTable.getModel();
        new ReadAccess().retrieveRentItem(RentTable, customerid);
        for (int i = 0; i < RentTable.getRowCount(); i++) {
            try {
                totalprice += Double.parseDouble(model.getValueAt(i, 3).toString());
            } catch (NumberFormatException e) {
                System.err.println("Invalid numeric value at row " + i + ", column 3");
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        RentTable = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        RowLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        RentTable.setBackground(new java.awt.Color(153, 153, 153));
        RentTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RentTable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "เลขไอดี", "วันที่เริ่มเช่า", "วันที่ต้องคืน", "ราคาเช่าเกิน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        RentTable.setFocusable(false);
        RentTable.setRowHeight(25);
        RentTable.setSelectionBackground(new java.awt.Color(153, 153, 153));
        RentTable.setSelectionForeground(new java.awt.Color(102, 102, 102));
        RentTable.getTableHeader().setReorderingAllowed(false);
        RentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RentTableMousePressed(evt);
            }
        });
        RentTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                RentTablePropertyChange(evt);
            }
        });
        jScrollPane5.setViewportView(RentTable);
        if (RentTable.getColumnModel().getColumnCount() > 0) {
            RentTable.getColumnModel().getColumn(0).setResizable(false);
            RentTable.getColumnModel().getColumn(1).setResizable(false);
            RentTable.getColumnModel().getColumn(2).setResizable(false);
            RentTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel7.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Row");

        RowLabel.setFont(new java.awt.Font("Segoe UI Symbol", 0, 36)); // NOI18N
        RowLabel.setForeground(new java.awt.Color(255, 255, 255));
        RowLabel.setText("-");

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/product-return.png"))); // NOI18N
        jLabel1.setText("Return item");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(RowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel7)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RowLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RentTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RentTableMousePressed
        selectedRows = RentTable.getSelectedRows();
        if (selectedRows.length > 0) {
            selectedRowsString = "";
            for (int row : selectedRows) {
                selectedRowsString += row + 1 + " ";
            }
            RowLabel.setText(selectedRowsString);
        }
    }//GEN-LAST:event_RentTableMousePressed

    private void RentTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_RentTablePropertyChange
        RentTable.getTableHeader().setFont(new Font("Tahoma", Font.PLAIN, 14));
        RentTable.getTableHeader().setBackground(new Color(153, 153, 153));
        RentTable.getTableHeader().setOpaque(false);
    }//GEN-LAST:event_RentTablePropertyChange

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        if (selectedRows != null && selectedRows.length > 0) {
            for (int selectedRow : selectedRows) {
                int equipmentID = Integer.parseInt((String) model.getValueAt(selectedRow, 0));
                int confirm = JOptionPane.showConfirmDialog(this, "Confirm to return row " + selectedRowsString + "?" + "\nTotal price: " + totalprice);
                if (confirm == JOptionPane.YES_OPTION) {
                    JOptionPane.showMessageDialog(this, "Order row " + selectedRowsString, "Equipment rental store", JOptionPane.ERROR_MESSAGE);
                    new SaveAccess().returnRental(equipmentID, customerid);
                    model.removeRow(selectedRow);
                }
            }
        }
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTable RentTable;
    private javax.swing.JLabel RowLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables
}
